config/routes.rb
Rails.application.routes.draw do
  root to: 'library_lists#index'

  get '/', to: 'library_lists#index'
  get '/new', to: 'library_lists#new'
  post '/new', to: 'library_lists#create'
  get '/*language', to: 'library_lists#index', as: 'language'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library_list.rb
class LibraryList < ApplicationRecord
  LANGUAGE      = 'language'
  CATEGORY      = 'category'
  REPO          = 'repo'
  URL_SEPARATOR = '/'

  scope :by_language, -> (language) { where("data -> 'language' ? :language", language: language) }
  scope :by_language_and_category, -> (language, category) do
    where("data -> 'language' ? :language AND data -> 'category' ? :category", language: language, category: category)
  end
  scope :select_distinct_language, -> { select("data -> 'language' as item").distinct }
  scope :select_distinct_language_and_category, -> do
    select("data -> 'category' as item", "data -> 'language' as language").distinct
  end
  scope :select_repo_attributes, -> do
    select(
        "data -> 'repo' as name",
        "data -> 'star_count' as star_count",
        "data -> 'fork_count' as fork_count",
        "data -> 'pushed_at' as pushed_at"
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/library_lists_controller.rb
class LibraryListsController < ApplicationController
  before_action :set_library_list_type, only: [:index, :create]
  before_action :set_library_list, only: :index

  def index
    render :index, locals: { library_list_type: @library_list_type }
  end

  def new
    @library_list = LibraryList.new
  end

  def create
    @library_list = LibraryList.new create_item_service.perform

    if @library_list.save
      set_library_list

      render :index, locals: { library_list_type: @library_list_type }
    else
      render :new
    end
  end

  private

  def permitted_params
    params.require(:library_list).permit(:language, :category, :repo)
  end

  def create_item_service
    LibraryLists::CreateItemService.new(permitted_params)
  end

  def set_library_list
    @library_lists = params[:language].present? ? find_by_language_path : LibraryList.select_distinct_language
  end

  def find_by_language_path
    if params[:language].include?(LibraryList::URL_SEPARATOR)
      LibraryList.by_language_and_category(library_path.first, library_path.last).select_repo_attributes
    else
      LibraryList.by_language(library_path.first).select_distinct_language_and_category
    end
  end

  def library_path
    params[:language].split(LibraryList::URL_SEPARATOR) if params[:language].present?
  end

  def set_library_list_type
    @library_list_type = params[:language].present? ? set_repo_or_category_type : LibraryList::LANGUAGE
  end

  def set_repo_or_category_type
    if params[:language].include?(LibraryList::URL_SEPARATOR)
      LibraryList::REPO
    else
      LibraryList::CATEGORY
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/library_lists/_form.html.erb
<%= form_with(url: new_path, model: library_list, local: true) do |form| %>
    <% if library_list.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(library_list.errors.count, "error") %> prohibited this library list from being saved:</h2>

          <ul>
            <% library_list.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :language %>
      <%= form.text_field :language, required: true %>
    </div>

    <div class="field">
      <%= form.label :category %>
      <%= form.text_field :category, required: true %>
    </div>

    <div class="field">
      <%= form.label :repo %>
      <%= form.text_field :repo, required: true %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/library_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Awesome List</h1>

<table>
  <thead>
  <tr>
    <% if library_list_type.eql?('language') %>
      <th>Language</th>
    <% elsif library_list_type.eql?('category') %>
      <th>Category</th>
    <% elsif library_list_type.eql?('repo') %>
      <th>Repo Name</th>
      <th>Star Count</th>
      <th>Fork Name</th>
      <th>Last Update</th>
    <% end %>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% @library_lists.each do |library_list| %>
      <tr>
        <% if library_list_type.eql?('language') %>
          <td><%= link_to library_list.item, language_path(library_list.item) %></td>
        <% elsif library_list_type.eql?('category') %>
          <td><%= link_to library_list.item, language_path("#{library_list.language}/#{library_list.item}") %></td>
        <% elsif library_list_type.eql?('repo') %>
          <td><%= library_list.name %></td>
          <td><%= library_list.star_count %></td>
          <td><%= library_list.fork_count %></td>
          <td><%= library_list.pushed_at %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Library', new_path %> |
<%= link_to 'Home', root_path %>

app/views/library_lists/new.html.erb
<h1>New Item</h1>

<%= render 'form', library_list: @library_list %>

<%= link_to 'Back to list', root_path %>